### ISSUE TITLE
Joern-queries scripts when run on Netx 5.7 stacks DNS code does not report any error.

### ISSUE THREAD

**Issue by RishaHolla** [Forescout/namewreck#1]
I am trying to run the joern-queries to detect NAME:WRECK vulnerability on Netx 5.7 stacks DNS files. But it is not reporting any error.

Steps followed:
Got to namewreck/joern-queries folder i installed from this git hub.
And open a joern cli with command joern. Attached further steps in image below. As you see below when i run main.exec() i dont see any NAME:WRECK complaints other than NAMEWRECK DETECTOR message. Pls help.

![image](https://user-images.githubusercontent.com/91676443/135499456-31a77612-1d6c-4aa3-b9b5-58281c76a531.png)

**Comment by standash** [comment]
Hi, it's possible that the code you are trying to analyze does not have the code patterns that we can detect. Is this a public project?
